[workspace]
resolver = "2"

members = [ 
    "assets/hello-fungi",
    "fungi",
    "fungi-config",
    "fungi-daemon",
    "fungi-gateway",
    "fungi-util",
    "fungi-wasi",
    "fungi/ffi/fungi-mobile-binding",
    "fungi/ffi/uniffi-bindgen",
]

[workspace.dependencies]
futures = "0.3"
log = "0.4"
once_cell = "1"
anyhow = "1"
bincode = "1.3"
rand = "0.8"
interprocess = { git = "https://github.com/kotauskas/interprocess", rev = "db6c36d1ccf86e607490e116d15ec7dbca1500af", features = ["tokio"] }
serde = { version = "1", features = ["derive"] }
libp2p-identity = "0.2"
multiaddr = "0.18"
