[workspace]
resolver = "2"

members = [ 
    "assets/hello-fungi",
    "fungi",
    "fungi-gateway",
    "fungi-util",
    "fungi-wasi",
]

[workspace.dependencies]
futures = "0.3"
log = "0.4"
once_cell = "1"
anyhow = "1"
bincode = "1.3"
rand = "0.8"
