[package]
name = "fungi-config"
version = "0.3.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
toml = "0.8"
libp2p-identity = { workspace = true }
multiaddr = "0.18"
fungi-util = { path = "../util" }
