apiVersion: fungi.rs/v1alpha1
kind: Service

metadata:
  name: filebrowser-lite-wasi

spec:
  run:
    wasmtime:
      url: https://github.com/enbop/filebrowser-lite/releases/download/lite-v0.2.0/filebrowser-lite-wasi.wasm

  entries:
    http:
      port: 8082
      usage: web
      path: /
      iconUrl: https://raw.githubusercontent.com/filebrowser/logo/master/icon.svg
      catalogId: io.enbop.filebrowser-lite-wasi

  mounts:
    - hostPath: ${USER_HOME}
      runtimePath: data

  env: {}

notes:
  - "Project: https://github.com/enbop/filebrowser-lite/tree/master/filebrowser-lite-wasi"
  - "Artifact URL: https://github.com/enbop/filebrowser-lite/releases/download/lite-v0.2.0/filebrowser-lite-wasi.wasm"
