[package]
name = "fungi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"]}
home = "0.5"
thiserror = "1.0"
fungi-gateway = { path = "../fungi-gateway" }
libp2p = { version = "0.53" , features = ["macros", "noise", "ping", "tcp", "quic", "tokio", "yamux", "serde"] }
libp2p-stream = "0.1.0-alpha"
futures = { workspace = true }