[package]
name = "fungi"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mush"
path = "src/bins/mush.rs"

[[bin]]
name = "fungi-daemon"
path = "src/bins/fungi-daemon.rs"

[[bin]]
name = "fungi-wasi"
path = "src/bins/fungi-wasi.rs"

[features]
default = ["tcp-tunneling"]
tcp-tunneling = []

[dependencies]
log = { workspace = true }
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
home = "0.5"
thiserror = "1.0"
fungi-config = { path = "../fungi-config" }
fungi-daemon = { path = "../fungi-daemon", features = ["cli"] }
fungi-gateway = { path = "../fungi-gateway" }
fungi-util = { path = "../fungi-util" }
fungi-wasi = { path = "../fungi-wasi" }
libp2p = { version = "0.53", features = [
    "macros",
    "noise",
    "ping",
    "tcp",
    "quic",
    "tokio",
    "yamux",
    "serde",
    "secp256k1",
] }
futures = { workspace = true }
bincode = { workspace = true }
interprocess = { workspace = true }
rand = { workspace = true }