[package]
name = "fungi"
version.workspace = true
edition.workspace = true
default-run = "fungi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
log = { workspace = true }
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
home = "0.5"
thiserror = { workspace = true }
fungi-config = { path = "../crates/config" }
fungi-daemon = { path = "../crates/daemon" }
fungi-swarm = { path = "../crates/swarm" }
fungi-util = { path = "../crates/util" }
libp2p = { workspace = true }
futures = { workspace = true }
bincode = { workspace = true }
interprocess = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
tarpc = { workspace = true }
libp2p-stream = { workspace = true }
