[package]
name = "fungi"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fungi-daemon"
path = "src/bins/fungi-daemon.rs"

[features]
default = ["daemon"]
daemon = ["fungi-daemon"]

[dependencies]
log = { workspace = true }
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
home = "0.5"
thiserror = "1.0"
fungi-config = { path = "../crates/config" }
fungi-daemon = { path = "../crates/daemon", features = [
    "cli",
], optional = true }
fungi-swarm = { path = "../crates/swarm" }
fungi-util = { path = "../crates/util" }
libp2p = { version = "0.53", features = [
    "macros",
    "noise",
    "ping",
    "tcp",
    "quic",
    "tokio",
    "yamux",
    "serde",
    "secp256k1",
] }
futures = { workspace = true }
bincode = { workspace = true }
interprocess = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
tarpc = { workspace = true }
