[package]
name = "fungi-config"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
toml = "0.8"
libp2p-identity = { workspace = true }
multiaddr = { workspace = true }