name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Set up Rust
      shell: bash
      run: rustup update stable --no-self-update && rustup default stable

    - name: Install protobuf compiler
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
        elif [ "${{ runner.os }}" = "macOS" ]; then
          brew untap aws/tap || true
          brew install protobuf
        elif [ "${{ runner.os }}" = "Windows" ]; then
          choco install protoc
        fi

    - name: Cache cargo registry
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache target folder
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: target
        key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-

    - name: Build
      run: cargo build

    - name: Run all tests
      run: |
        cargo test --all
